name: Container Image
on:
  push:
    branches:
      - main
    tags:
      - '*'
env:
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout git
      uses: actions/checkout@v2

    - name: Setup dependancies
      run: |
        curl -sLO https://github.com/prometheus/promu/releases/download/v0.15.0/promu-0.15.0.linux-amd64.tar.gz | tar xz
        mv promu-0.15.0.linux-amd64/promu /usr/bin/promu
        rm -rf promu-0.15.0.linux-amd64
    
    - name: Log in to the GH Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Container image metadata enrichment
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/namm2/azure-metrics-exporter
        tags: |
          type=sha
          type=ref,event=tag

    - name: Build and push image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
